### ISSUE TITLE
Application does not activate on click in dock

### ISSUE THREAD

**Issue by Arnoud-B** [steventheworker/Dock-Expos--home#11]
Hi,

Could you please enable the possibility to activate an application when clicking on its icon in the dock? Currently I can only activate them by hovering over the icon and then clicking on the preview, which requires an extra (and unnecessary) mouse movement. With my settings the preview shows immediately (and killing the dock makes no change to this behavior).

Thanks!

**Comment by steventheworker** [comment]
Just making sure, does this only happen for apps with exactly 1 **_minimized_** window? Or just mostly for minimized windows?

If so, it's the same issue as [#8](https://github.com/steventheworker/DockAltTab/issues/8) on DockAltTab.

**Comment by Arnoud-B** [comment]
No minimized windows. I can reproduce the issue with two Safari windows open.

**Comment by steventheworker** [comment]
So, this only happens when on a space w/ 0 windows? You'd like it to switch to the first preview's space? Because what it's doing right now, is bringing the most recent window (for the current space) forward, OR giving the app the menubar (activating the app).

This is the desired behavior?
https://user-images.githubusercontent.com/43100895/215694814-2905933d-b633-4013-a0b7-dd3ee1dda28d.mov

**Comment by Arnoud-B** [comment]
I have plenty of windows open, but none hidden. The behavior is not the same as in your video. Example:

1. Open Finder & Safari windows.
2. With Finder in the foreground, hover over the Safari icon in the dock (left-aligned for me).
3. When the Safari preview appears, click on the Safari icon in the dock.

Expected: Safari becomes the window in the foreground.
Actual: Safari preview disappears, Finder remains window in the foreground.

**Comment by steventheworker** [comment]
"Click dock icons to toggle showing & hiding apps" must be checked under Dock Exposé preferences. This also requires input monitoring permissions in Settings. If you already have these things enabled and it doesn't work try re-adding permissions: [like so](https://github.com/steventheworker/Dock-Expos--home/issues/10#issuecomment-1409869298)

**Comment by Arnoud-B** [comment]
Indeed, I had to re-add permissions. The accessibility toggle wasn't switched off by the Terminal command, so I switched it off/on manually. Thanks!

Not sure if it's expected behavior, but after click, the previous app zooms in from behind the preview before switching to the clicked app. Would be nice if it switched to the clicked app immediately after click, or the preview window is zoomed in. Feels like a glitch this way 😅

**Comment by steventheworker** [comment]
Yeah sometimes the terminal command doesn't work, hoping that isn't related to the permissions not applying 😥 maybe ```tccutil reset ListenEvent com.steventheworker.Dock-Expose``` & ```tccutil reset Accessibility com.steventheworker.Dock-Expose``` separately would work?

Also, that's because there's a 0.333 second delay in showing/hiding apps. I'm in the middle of removing it from DockAltTab [(issue 9)]() and will do the same on Dock Exposé right after.

Maybe using reduce motion (in Settings) and a delay could help, in the meantime.
