### ISSUE TITLE
Dock Delay and other questions

### ISSUE THREAD

**Issue by jhhtaylor** [steventheworker/Dock-Expos--home#20]
Hi @steventheworker 

Thanks for this app! It's something I have been wanting for a while, coming from Windows.

A few questions:
1 - I can't tell what the 'Dock Delay' at the bottom even does? It does not seem to change anything?
<img width="268" alt="Screenshot 2024-02-08 at 15 37 09" src="https://github.com/steventheworker/Dock-Expos--home/assets/29454433/831bb3e7-3bcd-4b4b-ada2-4654c33b9537">
I can see the 'Enable Previews' delay delays how long before the 'Application Windows' shows up
<img width="434" alt="Screenshot 2024-02-08 at 15 37 14" src="https://github.com/steventheworker/Dock-Expos--home/assets/29454433/567f1de6-1eb2-46a8-8816-f1d70642c79b">
2 - Once you have unticked the 'Add item to menu bar' checkbox, it seems impossible to get the Dock Expose preferences back unless you edit the configs using a terminal - or is there a simpler way I am missing?
<img width="153" alt="Screenshot 2024-02-08 at 15 37 28" src="https://github.com/steventheworker/Dock-Expos--home/assets/29454433/42b12476-9328-4879-a07c-5186ac38165e">
3 - Small UI nitpick - but if you go to the 'Links' button, the 'Dock Delay' selector can still be seen (MacBook Air M1)
<img width="473" alt="Screenshot 2024-02-08 at 15 42 08" src="https://github.com/steventheworker/Dock-Expos--home/assets/29454433/7219fe09-bed9-4e4f-a84d-dcdc9de01f50">

**Comment by steventheworker** [comment]
1. It's the delay for how long it takes for the dock to reveal (if you have autohide on). The default is 0.5, so I'm not sure why there's a comma between 0 and 5 for you.

Setting it to 0 immediately reveals the dock. You can also set it to a really high number, to effectively disable the dock.

2. This is fixed in a major upgrade (v3) I will release sometime this week.

3. The update will lose some features such as the links menu. (might re-add as a popup window to avoid this though)
... as well as this delay slider 
![image](https://github.com/steventheworker/Dock-Expos--home/assets/43100895/163c1be6-dc0b-4ed8-9094-4a0c13ed3b18)
which I plan to add back by v3.01 a week or so later.

**Comment by jhhtaylor** [comment]
1. Oh okay - I don't have autohide on - that's why it does not work. Also - adding '0.5' gives me this error - must be a region setting that I have
<img width="482" alt="Screenshot 2024-02-09 at 08 07 53" src="https://github.com/steventheworker/Dock-Expos--home/assets/29454433/b520d25e-25d3-4c9a-b65b-b7cd03ec404f">

2., 3. Great!
