### ISSUE TITLE
Open-source?

### ISSUE THREAD

**Issue by djsrv** [steventheworker/Dock-Expos--home#3]
Is the app itself open-source? The website has a "Support Free Open Source Software" link, suggesting it is, but I don't see any source code except for the website.

**Comment by steventheworker** [comment]
No it's technically not open source and this repo is for the website / getting update reminders via GitHub.

I go back and forth on whether or not to share it, but have chosen not to for the foreseeable future since DockAltTab is already open source and both apps have the same [starting point / shared code](https://github.com/steventheworker/DockAltTab/commit/c97278f2b87d492fb21fd2af97d30df44535d18c). The code I'm withholding mostly has to do with opening App Exposé which shouldn't be too hard to figure out, but I also spent days figuring out how to handle Exposé windows, and am not comfortable sharing until I can find some actual programming work or Dock Exposé becomes popular enough to not care whether or not it's cloned.
