### ISSUE TITLE
Why Dock Exposé is So Internet Hungry?

### ISSUE THREAD

**Issue by Maghsad** [steventheworker/Dock-Expos--home#6]
Hi,

Thanks for developing Dock Exposé. Without connecting to the internet, Dock Exposé goes not responsive and takes a long time to come back to life. Without connecting to Wi-Fi, even opening Dock Exposé's preferences takes a considerably long time since it goes unresponsive.

**Could you please let me know why Dock Exposé extremely internet hungry?** 

Thanks

**Comment by steventheworker** [comment]
I usually am not without internet, and since no one else has brought this up, I never really put much thought into the simple updater (on start up these dock apps read [currentversion.txt](https://dockexpose.netlify.app/currentversion.txt) for the latest version and does it synchronously. So if you have no wifi it clogs the thread until macOS decides to kill the request. Will fix soon!

**Comment by Maghsad** [comment]
Hi @steventheworker,

Thanks for your prompt response. Could you make sending data optional? Many software such as Rectangle, have options to disable automatic checks for updates. 

Thanks again for developing this useful app.

<img src="https://i.ibb.co/zXJZ8Yq/SCR-20221121-ffs.png" alt="SCR-20221121-ffs" border="0" />

**Comment by steventheworker** [comment]
Patched in v2.92.
